import os
import json
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import joblib

# Comprehensive Authentic 15+ POIs per Destination (Zero generic templates)
ALL_REAL_POIS = [
    # ==================== PARIS, FRANCE ====================
    {"poi_id": "PAR_01", "name": "Eiffel Tower & Champ de Mars", "city": "Paris", "region": "Europe", "country": "France", "category": "Iconic Landmark", "rating": 4.9, "entry_fee_inr": 2400, "ideal_duration_hrs": 3.0, "lat": 48.8584, "lon": 2.2945, "tags": "iron lady, summit elevator, champagne bar, sparkling lights, trocadero view, paris", "description": "Gustave Eiffel's 330-meter iron masterpiece offering panoramic city vistas across Paris, champagne summit bars, and nightly sparkle shows."},
    {"poi_id": "PAR_02", "name": "Louvre Museum & Glass Pyramid", "city": "Paris", "region": "Europe", "country": "France", "category": "Art & History", "rating": 4.9, "entry_fee_inr": 1800, "ideal_duration_hrs": 4.0, "lat": 48.8606, "lon": 2.3376, "tags": "mona lisa, venus de milo, winged victory, i.m. pei pyramid, french royal palace, paris", "description": "The world's most visited museum displaying over 35,000 masterpieces including Leonardo da Vinci's Mona Lisa and the ancient Winged Victory."},
    {"poi_id": "PAR_03", "name": "Montmartre & Sacré-Cœur Basilica", "city": "Paris", "region": "Europe", "country": "France", "category": "Heritage & Bohemian", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 3.0, "lat": 48.8867, "lon": 2.3431, "tags": "artists square, place du tertre, white travertine basilica, moulin rouge, hill view, paris", "description": "Bohemian hilltop village where Picasso and Van Gogh painted, crowned by the Romano-Byzantine white domed Sacré-Cœur with panoramic city views."},
    {"poi_id": "PAR_04", "name": "Seine River Evening Cruise & Pont Alexandre III", "city": "Paris", "region": "Europe", "country": "France", "category": "Scenic & Romance", "rating": 4.8, "entry_fee_inr": 1400, "ideal_duration_hrs": 2.0, "lat": 48.8640, "lon": 2.3135, "tags": "illuminated monuments, bateaux mouches, gilded statues, bridges, sunset cruise, paris", "description": "Glide under 37 historic bridges past Notre-Dame, Musée d'Orsay, and Grand Palais bathed in golden evening illuminations."},
    {"poi_id": "PAR_05", "name": "Palace of Versailles & Hall of Mirrors", "city": "Paris", "region": "Europe", "country": "France", "category": "Royal Heritage", "rating": 4.9, "entry_fee_inr": 2200, "ideal_duration_hrs": 5.0, "lat": 48.8049, "lon": 2.1204, "tags": "hall of mirrors, royal apartments, fountains show, king louis xiv, formal gardens, paris", "description": "Sun King Louis XIV's opulent 2,300-room royal chateau showcasing the 73-meter Hall of Mirrors and vast classical fountains."},
    {"poi_id": "PAR_06", "name": "Arc de Triomphe & Champs-Élysées", "city": "Paris", "region": "Europe", "country": "France", "category": "Monuments & Luxury", "rating": 4.7, "entry_fee_inr": 1100, "ideal_duration_hrs": 2.0, "lat": 48.8738, "lon": 2.2950, "tags": "napoleonic arch, tomb of unknown soldier, rooftop view, 12 radiating avenues, shopping, paris", "description": "Napoleonic triumphal arch honoring French victories, offering rooftop views across the 12 radiating grand avenues and Champs-Élysées."},
    {"poi_id": "PAR_07", "name": "Latin Quarter & Luxembourg Gardens", "city": "Paris", "region": "Europe", "country": "France", "category": "Parks & Historic", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 48.8462, "lon": 2.3372, "tags": "sorbonne, medici fountain, tree lined gravel paths, shakespeare and co bookshop, cafes, paris", "description": "Historic student quarter filled with legendary cafes, Shakespeare & Company bookstore, and Marie de' Medici's Italianate palace gardens."},
    {"poi_id": "PAR_08", "name": "Musée d'Orsay Impressionist Masterpieces", "city": "Paris", "region": "Europe", "country": "France", "category": "Fine Art", "rating": 4.9, "entry_fee_inr": 1600, "ideal_duration_hrs": 3.0, "lat": 48.8599, "lon": 2.3265, "tags": "monet, van gogh, renoir, converted beaux-arts railway station, giant clock face, paris", "description": "Converted Beaux-Arts railway station housing the world's finest collection of Impressionist and Post-Impressionist paintings by Monet, Van Gogh, and Renoir."},
    {"poi_id": "PAR_09", "name": "Notre-Dame Cathedral & Île de la Cité", "city": "Paris", "region": "Europe", "country": "France", "category": "Gothic Architecture", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 2.0, "lat": 48.8529, "lon": 2.3499, "tags": "gothic cathedral, gargoyles, rose windows, seine island, point zero of france, paris", "description": "Medieval Catholic cathedral on Île de la Cité island, a French Gothic masterpiece famous for its gargoyles and flying buttresses."},
    {"poi_id": "PAR_10", "name": "Sainte-Chapelle Stained Glass Windows", "city": "Paris", "region": "Europe", "country": "France", "category": "Gothic Jewel", "rating": 4.9, "entry_fee_inr": 1200, "ideal_duration_hrs": 1.5, "lat": 48.8554, "lon": 2.3450, "tags": "13th century royal chapel, 1113 biblical stained glass scenes, gothic gem, conciergerie, paris", "description": "13th-century Gothic royal chapel containing 15 towering stained glass windows with 1,113 biblical scenes that flood the upper sanctuary with vibrant colored light."},
    {"poi_id": "PAR_11", "name": "Centre Pompidou Modern Art & Rooftop", "city": "Paris", "region": "Europe", "country": "France", "category": "Modern Art", "rating": 4.7, "entry_fee_inr": 1500, "ideal_duration_hrs": 2.5, "lat": 48.8606, "lon": 2.3522, "tags": "inside out architecture, kandinsky, picasso, matisse, rooftop panorama, stravinsky fountain, paris", "description": "High-tech inside-out architecture housing Europe's largest modern and contemporary art museum, featuring works by Picasso, Kandinsky, and Matisse."},
    {"poi_id": "PAR_12", "name": "Palais Garnier National Opera House", "city": "Paris", "region": "Europe", "country": "France", "category": "Grand Architecture", "rating": 4.8, "entry_fee_inr": 1400, "ideal_duration_hrs": 2.0, "lat": 48.8719, "lon": 2.3316, "tags": "phantom of the opera, grand marble staircase, chagall painted ceiling, gold leaf foyer, paris", "description": "1,979-seat opera house built for Emperor Napoleon III, famous for its magnificent marble Grand Staircase and Marc Chagall's ceiling mural."},
    {"poi_id": "PAR_13", "name": "Catacombs of Paris Underground Labyrinth", "city": "Paris", "region": "Europe", "country": "France", "category": "Historic Underground", "rating": 4.7, "entry_fee_inr": 2200, "ideal_duration_hrs": 2.0, "lat": 48.8338, "lon": 2.3324, "tags": "underground ossuary, 6 million skeletons, limestone tunnels, 20m depth, macabre history, paris", "description": "Underground ossuaries holding the remains of more than six million people in a network of historic limestone mining caverns."},
    {"poi_id": "PAR_14", "name": "Le Marais Historic Mansions & Place des Vosges", "city": "Paris", "region": "Europe", "country": "France", "category": "Heritage & Dining", "rating": 4.8, "entry_fee_inr": 0, "avg_spend_inr": 1200, "ideal_duration_hrs": 2.5, "lat": 48.8556, "lon": 2.3653, "tags": "victor hugo house, red brick arcades, falafel, art boutiques, historic courtyard mansions, paris", "description": "Fashionable historic district with 17th-century aristocratic mansions, Paris's oldest planned square (Place des Vosges), and artisan pastry shops."},
    {"poi_id": "PAR_15", "name": "Tuileries Garden & Musée de l'Orangerie", "city": "Paris", "region": "Europe", "country": "France", "category": "Parks & Monet", "rating": 4.8, "entry_fee_inr": 1250, "ideal_duration_hrs": 2.5, "lat": 48.8638, "lon": 2.3275, "tags": "claude monet water lilies, formal french gardens, green park chairs, louvre connection, paris", "description": "Historic public garden between the Louvre and Place de la Concorde, housing Monet's eight monumental Water Lilies murals in oval galleries."},

    # ==================== SWITZERLAND ====================
    {"poi_id": "SWI_01", "name": "Zurich Old Town (Altstadt) & Lindenhof Hill", "city": "Zurich", "region": "Switzerland", "country": "Switzerland", "category": "Heritage & Culture", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 2.5, "lat": 47.3717, "lon": 8.5411, "tags": "medieval guild houses, grossmunster twin towers, fraumunster chagall windows, limmat river, switzerland", "description": "Historic medieval lanes lined with guild houses, Grossmünster twin towers, Fraumünster's Chagall windows, and Lindenhof hilltop vistas."},
    {"poi_id": "SWI_02", "name": "Lake Zurich Sunset Promenade & Steam Cruise", "city": "Zurich", "region": "Switzerland", "country": "Switzerland", "category": "Lake Cruise", "rating": 4.7, "entry_fee_inr": 1200, "ideal_duration_hrs": 2.0, "lat": 47.3667, "lon": 8.5417, "tags": "steamboat cruise, alps backdrop, bürkliplatz, lakeside parks, sunset waters, switzerland", "description": "Scenic cruise on Lake Zurich with panoramic views of the distant Swiss Alps, departing from Bürkliplatz harbor."},
    {"poi_id": "SWI_03", "name": "Chapel Bridge (Kapellbrücke) & Water Tower Lucerne", "city": "Lucerne", "region": "Switzerland", "country": "Switzerland", "category": "Historic Landmark", "rating": 4.9, "entry_fee_inr": 0, "ideal_duration_hrs": 2.0, "lat": 47.0516, "lon": 8.3075, "tags": "14th century wooden bridge, painted roof panels, octagonal water tower, reuss river, switzerland", "description": "Europe's oldest covered wooden bridge dating to the 14th century, containing 17th-century triangular painted panels depicting Swiss history."},
    {"poi_id": "SWI_04", "name": "Mount Pilatus Golden Roundtrip Cableway (2,128m)", "city": "Lucerne", "region": "Switzerland", "country": "Switzerland", "category": "Alpine Mountain Peak", "rating": 4.9, "entry_fee_inr": 6500, "ideal_duration_hrs": 4.5, "lat": 46.9799, "lon": 8.2536, "tags": "world steepest cogwheel railway 48% gradient, dragon ride cable car, alpine panorama, switzerland", "description": "Ascend via the world's steepest cogwheel railway (48% gradient) to 2,128m for 360-degree views of 73 Alpine mountain summits."},
    {"poi_id": "SWI_05", "name": "Jungfraujoch - Top of Europe & Ice Palace (3,454m)", "city": "Interlaken", "region": "Switzerland", "country": "Switzerland", "category": "High Alpine Glacier", "rating": 5.0, "entry_fee_inr": 14000, "ideal_duration_hrs": 6.0, "lat": 46.5475, "lon": 7.9825, "tags": "highest railway station in europe 3454m, aletsch glacier 23km, ice palace sculptures, sphinx observatory, switzerland", "description": "UNESCO World Heritage glacier saddle at 3,454m featuring the Great Aletsch Glacier (Europe's longest), sculpted Ice Palace, and Sphinx Observatory."},
    {"poi_id": "SWI_06", "name": "Lauterbrunnen Valley & Staubbach 300m Falls", "city": "Interlaken", "region": "Switzerland", "country": "Switzerland", "category": "Alpine Valley & Falls", "rating": 4.9, "entry_fee_inr": 0, "ideal_duration_hrs": 3.5, "lat": 46.5939, "lon": 7.9091, "tags": "valley of 72 waterfalls, staubbach 300m plunge, tolkien rivendell inspiration, wooden chalets, switzerland", "description": "Picturesque alpine trough valley flanked by vertical rock cliffs with 72 waterfalls, inspiring Tolkien's Rivendell."},
    {"poi_id": "SWI_07", "name": "Zermatt Village & Matterhorn Glacier Paradise (3,883m)", "city": "Zermatt", "region": "Switzerland", "country": "Switzerland", "category": "Iconic Peak & Glaciers", "rating": 5.0, "entry_fee_inr": 9500, "ideal_duration_hrs": 5.0, "lat": 45.9383, "lon": 7.7297, "tags": "matterhorn 4478m pyramid peak, car-free village, highest cable car in europe 3883m, glacier palace, switzerland", "description": "Car-free alpine paradise under the iconic pyramid of the Matterhorn, boasting Europe's highest cable car station at 3,883m."},
    {"poi_id": "SWI_08", "name": "Gornergrat 3,089m Scenic Alpine Cogwheel Railway", "city": "Zermatt", "region": "Switzerland", "country": "Switzerland", "category": "Alpine Railway", "rating": 4.9, "entry_fee_inr": 7200, "ideal_duration_hrs": 4.0, "lat": 45.9839, "lon": 7.7844, "tags": "open-air electric cogwheel train, 29 four-thousand meter peaks view, riffelsee lake matterhorn reflection, switzerland", "description": "Open-air electric cogwheel train climbing to 3,089m with views of 29 four-thousand-meter mountain peaks and Riffelsee lake reflections."},
    {"poi_id": "SWI_09", "name": "Bern Medieval Old City & Zytglogge Astronomical Clock", "city": "Bern", "region": "Switzerland", "country": "Switzerland", "category": "UNESCO Medieval City", "rating": 4.8, "entry_fee_inr": 0, "ideal_duration_hrs": 3.0, "lat": 46.9479, "lon": 7.4474, "tags": "unesco capital, 6km sandstone arcades, 13th century mechanical clock tower, barengraben bear park, switzerland", "description": "Switzerland's federal capital with 6km of covered sandstone arcades, 13th-century Zytglogge clock tower, and Bärengraben bear park."},
    {"poi_id": "SWI_10", "name": "Lake Brienz Turquoise Steamboat & Giessbach Falls", "city": "Interlaken", "region": "Switzerland", "country": "Switzerland", "category": "Lake & Waterfalls", "rating": 4.8, "entry_fee_inr": 1800, "ideal_duration_hrs": 3.5, "lat": 46.7333, "lon": 8.0167, "tags": "turquoise glacial water, historic paddle steamer, 14-stage giessbach waterfall, grandhotel, switzerland", "description": "Cruise turquoise glacial waters on a vintage paddle steamer to the 14-stage Giessbach Waterfall cascading into the lake."},
    {"poi_id": "SWI_11", "name": "Château de Chillon on Lake Geneva (Montreux)", "city": "Montreux", "region": "Switzerland", "country": "Switzerland", "category": "Lakeside Castle", "rating": 4.8, "entry_fee_inr": 1300, "ideal_duration_hrs": 2.5, "lat": 46.4142, "lon": 6.9275, "tags": "12th century island fortress, lord byron prisoner of chillon, lake geneva shores, dungeon vaults, switzerland", "description": "Romantic 12th-century island castle on Lake Geneva made famous by Lord Byron, featuring Gothic underground dungeons and courtyards."},
    {"poi_id": "SWI_12", "name": "Interlaken Harder Kulm Two Lakes Bridge Viewpoint", "city": "Interlaken", "region": "Switzerland", "country": "Switzerland", "category": "Panorama Bridge", "rating": 4.8, "entry_fee_inr": 3200, "ideal_duration_hrs": 2.5, "lat": 46.6975, "lon": 7.8528, "tags": "funicular railway, two lakes view thun and brienz, eiger monch jungfrau trio panorama, glass floor, switzerland", "description": "Glass-floored viewing platform suspended 1,322m above Interlaken with panoramic views over Lake Thun, Lake Brienz, and the Jungfrau trio."},
    {"poi_id": "SWI_13", "name": "Grindelwald First Cliff Walk by Tissot", "city": "Grindelwald", "region": "Switzerland", "country": "Switzerland", "category": "Suspension Cliff Walk", "rating": 4.9, "entry_fee_inr": 3800, "ideal_duration_hrs": 3.5, "lat": 46.6592, "lon": 8.0531, "tags": "metal walkway clinging to cliffside, 45m single-rope suspension bridge, first glider flyer, switzerland", "description": "Thrilling single-rope suspension bridge and metal walkway clinging to vertical cliffs 2,168m above Grindelwald valley."},
    {"poi_id": "SWI_14", "name": "Rhine Falls & Laufen Castle (Europe's Largest Waterfall)", "city": "Schaffhausen", "region": "Switzerland", "country": "Switzerland", "category": "Mighty Waterfalls", "rating": 4.7, "entry_fee_inr": 900, "ideal_duration_hrs": 3.0, "lat": 47.6778, "lon": 8.6156, "tags": "europe largest plain waterfall, 150m width, middle rock boat ride, roaring mist, laufen castle, switzerland", "description": "Europe's most powerful waterfall spanning 150 meters across the Rhine River with rock-island boat rides directly into the roaring spray."},
    {"poi_id": "SWI_15", "name": "Mount Titlis Rotair Revolving Cable Car & Cliff Walk", "city": "Engelberg", "region": "Switzerland", "country": "Switzerland", "category": "Revolving Cableway", "rating": 4.9, "entry_fee_inr": 7800, "ideal_duration_hrs": 4.5, "lat": 46.7722, "lon": 8.4375, "tags": "world first revolving cable car, titlis cliff walk highest suspension bridge 3041m, glacier cave, switzerland", "description": "Ride the world's first revolving Titlis Rotair cable car to 3,020m and cross Europe's highest suspension bridge over a 500m abyss."},

    # ==================== JAIPUR, RAJASTHAN ====================
    {"poi_id": "JAI_01", "name": "Amber Fort (Amer Palace) & Sheesh Mahal", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Hilltop Fortress", "rating": 4.9, "entry_fee_inr": 500, "ideal_duration_hrs": 3.5, "lat": 26.9855, "lon": 75.8513, "tags": "amer fort, sheesh mahal thousand mirrors, elephant ramp, maota lake, mughal rajput architecture, jaipur", "description": "Magnificent 16th-century hilltop fortress built of red sandstone and marble, famed for the Sheesh Mahal (Hall of Mirrors) and Maota Lake views."},
    {"poi_id": "JAI_02", "name": "Hawa Mahal (Palace of Winds)", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Iconic Monument", "rating": 4.8, "entry_fee_inr": 200, "ideal_duration_hrs": 1.5, "lat": 26.9239, "lon": 75.8267, "tags": "palace of winds, 953 pink sandstone jharokhas windows, royal women breeze, pink city, jaipur", "description": "Five-storey pink sandstone crown-shaped palace featuring 953 intricately carved lattice jharokha windows designed for royal ladies to observe street life."},
    {"poi_id": "JAI_03", "name": "City Palace & Chandra Mahal Museum", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Royal Palace", "rating": 4.8, "entry_fee_inr": 700, "ideal_duration_hrs": 2.5, "lat": 26.9258, "lon": 75.8236, "tags": "royal residence of maharaja, peacock gate, diwan-i-khas silver urns guinness record, courtyards, jaipur", "description": "Opulent complex of courtyards, gardens, and palaces where the titular Maharaja still resides, featuring the famous Peacock Gate."},
    {"poi_id": "JAI_04", "name": "Jantar Mantar UNESCO Astronomical Observatory", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "UNESCO Science", "rating": 4.7, "entry_fee_inr": 200, "ideal_duration_hrs": 2.0, "lat": 26.9248, "lon": 75.8246, "tags": "unesco world heritage, largest stone sundial vrihat samrat yantra 27m, 19 astronomical instruments, jaipur", "description": "18th-century UNESCO observatory containing 19 architectural astronomical instruments, including the world's largest stone sundial measuring time to 2-second accuracy."},
    {"poi_id": "JAI_05", "name": "Nahargarh Fort Sunset Point Over Pink City", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Sunset Fortress", "rating": 4.8, "entry_fee_inr": 200, "ideal_duration_hrs": 2.5, "lat": 26.9378, "lon": 75.8156, "tags": "aravali hills edge, stepwell padao restaurant, madhavendra bhawan 12 queen suites, rang de basanti spot, jaipur", "description": "Perched on the rugged Aravali ridge overlooking the entire Pink City, offering legendary golden sunsets and 12 identical suites for royal queens."},
    {"poi_id": "JAI_06", "name": "Jal Mahal (Water Palace) & Promenade", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Scenic Water Palace", "rating": 4.6, "entry_fee_inr": 0, "ideal_duration_hrs": 1.5, "lat": 26.9535, "lon": 75.8462, "tags": "man sagar lake, submerged 4 storeys underwater, illuminated night view, street handicrafts, jaipur", "description": "Stunning 18th-century Rajput palace appearing to float in the middle of Man Sagar Lake, surrounded by the Aravali hills."},
    {"poi_id": "JAI_07", "name": "Jaigarh Fort & World's Largest Jaivana Cannon", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Military Fort", "rating": 4.7, "entry_fee_inr": 150, "ideal_duration_hrs": 2.0, "lat": 26.9850, "lon": 75.8456, "tags": "fort of victory, jaivana cannon on wheels 50 tons, subterranean water tanks, armory museum, jaipur", "description": "Formidable 'Fort of Victory' built to protect Amer Fort, housing the 50-ton Jaivana Cannon (world's largest cannon on wheels)."},
    {"poi_id": "JAI_08", "name": "Panna Meena Ka Kund Ancient Stepwell", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Ancient Stepwell", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 1.0, "lat": 26.9867, "lon": 75.8567, "tags": "16th century geometric criss-cross stairs, stepwell photography, amer village, jaipur", "description": "Photogenic 16th-century stepwell featuring symmetrical zigzag criss-cross staircases, an ancient Rajasthani rainwater harvesting marvel."},
    {"poi_id": "JAI_09", "name": "Albert Hall Central Museum & Ram Niwas Garden", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Museum & Gardens", "rating": 4.7, "entry_fee_inr": 300, "ideal_duration_hrs": 2.0, "lat": 26.9117, "lon": 75.8194, "tags": "indo-saracenic architecture, egyptian mummy, miniature paintings, pigeons flock, night illumination, jaipur", "description": "Rajasthan's oldest museum housed in magnificent Indo-Saracenic building displaying ivory, miniature paintings, crystal, and a 2,300-year-old Egyptian mummy."},
    {"poi_id": "JAI_10", "name": "Galta Ji (Monkey Temple) & Sacred Kunds", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Sacred Springs", "rating": 4.6, "entry_fee_inr": 0, "ideal_duration_hrs": 2.0, "lat": 26.9167, "lon": 75.8583, "tags": "natural freshwater springs, sacred bathing tanks, rhesus macaque monkeys, mountain gorge, sun temple, jaipur", "description": "Ancient Hindu pilgrimage center nestled in a narrow mountain pass, famed for seven natural water kunds and friendly resident monkey tribes."},
    {"poi_id": "JAI_11", "name": "Birla Mandir (Laxmi Narayan) & Moti Dungri", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Marble Temple", "rating": 4.7, "entry_fee_inr": 0, "ideal_duration_hrs": 1.5, "lat": 26.8925, "lon": 75.8153, "tags": "pure white makrana marble temple, ganesh temple, stained glass mythological scenes, jaipur", "description": "Gleaming white Makrana marble modern temple dedicated to Lord Vishnu and Goddess Lakshmi, glowing at night at the base of Moti Dungri hill."},
    {"poi_id": "JAI_12", "name": "Johari Bazaar & Bapu Bazaar Artisan Shopping", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Bazaars & Crafts", "rating": 4.6, "entry_fee_inr": 0, "avg_spend_inr": 2000, "ideal_duration_hrs": 2.5, "lat": 26.9200, "lon": 75.8250, "tags": "gemstones jewelry, jaipuri quilts razai, bandhani textiles, camel leather juttis, street shopping, jaipur", "description": "Vibrant pink-arcaded markets famous for precious colored gemstones, handcrafted Jaipuri cotton quilts, block prints, and camel leather footwear."},
    {"poi_id": "JAI_13", "name": "Chokhi Dhani Ethnic Rajasthani Village & Thali Feast", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Cultural Resort & Dining", "rating": 4.8, "entry_fee_inr": 1200, "ideal_duration_hrs": 4.0, "lat": 26.7667, "lon": 75.8333, "tags": "authentic village experience, ghoomar fire dance, camel rides, dal baati churma royal feast, puppet show, jaipur", "description": "Immersive 5-star ethnic village resort offering Kalbeliya folk dances, acrobatics, puppet shows, camel rides, and unlimited royal Dal Baati Churma feasts."},
    {"poi_id": "JAI_14", "name": "Sisodia Rani Garden & Royal Cascades", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Royal Garden", "rating": 4.5, "entry_fee_inr": 100, "ideal_duration_hrs": 1.5, "lat": 26.8833, "lon": 75.8667, "tags": "multi-tiered mughal-style garden, radha krishna murals, natural spring fountains, royal retreat, jaipur", "description": "Multi-terraced royal garden with painted pavilions depicting Radha-Krishna romance, surrounded by lush wooded hills."},
    {"poi_id": "JAI_15", "name": "Royal Gaitor Cenotaphs (Chhatris of Maharajas)", "city": "Jaipur", "region": "Rajasthan", "country": "India", "category": "Marble Cenotaphs", "rating": 4.7, "entry_fee_inr": 100, "ideal_duration_hrs": 1.5, "lat": 26.9400, "lon": 75.8300, "tags": "white marble chhatris, carved dome cenotaphs, maharaja sawai jai singh ii memorial, quiet peaceful, jaipur", "description": "Peaceful valley sanctuary with intricately carved white marble domed cenotaphs commemorating the Kachhwaha Rajput rulers of Jaipur."}
]

def build_all():
    os.makedirs("datasets/destinations", exist_ok=True)
    os.makedirs("backend/app/ml/saved_models", exist_ok=True)

    merged_pois = {}
    if os.path.exists("datasets/destinations/destinations_rich_knowledge.json"):
        with open("datasets/destinations/destinations_rich_knowledge.json", "r", encoding="utf-8") as f:
            for p in json.load(f):
                if "Special" not in p.get("name", "") and "Highlight" not in p.get("name", ""):
                    merged_pois[p["name"]] = p

    for p in ALL_REAL_POIS:
        merged_pois[p["name"]] = p

    final_pois = list(merged_pois.values())
    print(f"[OK] Total unique authentic POIs: {len(final_pois)}")

    with open("datasets/destinations/destinations_rich_knowledge.json", "w", encoding="utf-8") as f:
        json.dump(final_pois, f, indent=2, ensure_ascii=False)

    df = pd.DataFrame(final_pois)
    df.to_csv("datasets/destinations/destinations_attractions.csv", index=False)
    print(f"[OK] Saved destinations_attractions.csv with {len(df)} records across {df['city'].nunique()} cities!")

    corpus = [
        f"{d['name']} in {d['city']}, {d.get('state', '')}, {d['country']}. Category: {d['category']}. Tags: {d.get('tags', '')}. {d['description']}"
        for d in final_pois
    ]
    vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))
    tfidf_matrix = vectorizer.fit_transform(corpus)
    joblib.dump(vectorizer, "backend/app/ml/saved_models/destinations_tfidf_vectorizer.joblib")
    joblib.dump(tfidf_matrix, "backend/app/ml/saved_models/destinations_tfidf_matrix.joblib")
    print(f"[OK] Trained TF-IDF vector matrix on {len(corpus)} documents with shape {tfidf_matrix.shape}")

    sim_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)
    joblib.dump(sim_matrix, "backend/app/ml/saved_models/destinations_similarity_matrix.joblib")
    print(f"[OK] Trained Recommender similarity matrix with shape {sim_matrix.shape}")

if __name__ == "__main__":
    build_all()
