import json
import os

# Comprehensive authentic POI Knowledge Base for Global & Domestic Destinations
ALL_DESTINATIONS_POIS = [
    # ==================== JAPAN (Tokyo, Kyoto, Osaka, Mount Fuji, Nara) ====================
    {
        "poi_id": "JPN_01",
        "name": "Sensō-ji Temple & Nakamise Dori",
        "city": "Japan",
        "state": "Tokyo",
        "country": "Japan",
        "category": "Heritage & Culture",
        "rating": 4.8,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.5,
        "lat": 35.7148,
        "lon": 139.7967,
        "tags": "temple, history, culture, souvenir market, architecture",
        "description": "Tokyo's oldest and most significant ancient Buddhist temple founded in 628 AD, approached via the bustling Nakamise shopping street."
    },
    {
        "poi_id": "JPN_02",
        "name": "Fushimi Inari-taisha Shrine",
        "city": "Japan",
        "state": "Kyoto",
        "country": "Japan",
        "category": "Heritage & Nature",
        "rating": 4.9,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 3.0,
        "lat": 34.9671,
        "lon": 135.7727,
        "tags": "torii gates, mountain hike, shrine, spiritual, photography",
        "description": "World-renowned Shinto shrine famous for its mesmerizing pathway of thousands of vermilion torii gates winding up Mount Inari."
    },
    {
        "poi_id": "JPN_03",
        "name": "Shibuya Crossing & Hachiko Statue",
        "city": "Japan",
        "state": "Tokyo",
        "country": "Japan",
        "category": "Urban & Modern",
        "rating": 4.7,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 1.5,
        "lat": 35.6595,
        "lon": 139.7005,
        "tags": "iconic scramble, city lights, hachiko, shopping, neon",
        "description": "The world's busiest pedestrian scramble intersection flanked by giant video screens, bustling neon billboards, and the loyal Hachiko bronze dog statue."
    },
    {
        "poi_id": "JPN_04",
        "name": "Kinkaku-ji (The Golden Pavilion)",
        "city": "Japan",
        "state": "Kyoto",
        "country": "Japan",
        "category": "Heritage & Zen Gardens",
        "rating": 4.8,
        "entry_fee_inr": 400,
        "ideal_duration_hrs": 2.0,
        "lat": 35.0394,
        "lon": 135.7292,
        "tags": "gold pavilion, zen garden, unesco, mirror pond, architecture",
        "description": "UNESCO World Heritage Zen Buddhist temple whose top two floors are completely covered in pure gold leaf, reflecting majestically over the Kyōko-chi pond."
    },
    {
        "poi_id": "JPN_05",
        "name": "Arashiyama Bamboo Grove & Monkey Park",
        "city": "Japan",
        "state": "Kyoto",
        "country": "Japan",
        "category": "Nature & Wildlife",
        "rating": 4.8,
        "entry_fee_inr": 500,
        "ideal_duration_hrs": 3.0,
        "lat": 35.0170,
        "lon": 135.6713,
        "tags": "bamboo forest, scenic walk, wild monkeys, river view",
        "description": "Towering natural green bamboo stalks soaring skyward create an ethereal soundscape, paired with a short hike to view wild Japanese macaques."
    },
    {
        "poi_id": "JPN_06",
        "name": "Tokyo Skytree & Solamachi",
        "city": "Japan",
        "state": "Tokyo",
        "country": "Japan",
        "category": "Skyline & Observation",
        "rating": 4.7,
        "entry_fee_inr": 1800,
        "ideal_duration_hrs": 2.5,
        "lat": 35.7101,
        "lon": 139.8107,
        "tags": "skyline, 634m tower, panoramic views, mount fuji view",
        "description": "The world's second-tallest freestanding structure standing 634 meters high, offering 360-degree panoramic glass vistas across the Kanto plain and Mount Fuji."
    },
    {
        "poi_id": "JPN_07",
        "name": "Tsukiji Outer Market & Ginza Dining",
        "city": "Japan",
        "state": "Tokyo",
        "country": "Japan",
        "category": "Culinary & Food",
        "rating": 4.8,
        "entry_fee_inr": 1200,
        "ideal_duration_hrs": 2.5,
        "lat": 35.6654,
        "lon": 139.7707,
        "tags": "sushi, street food, wagyu beef, seafood, culinary tour",
        "description": "Historic seafood haven lined with over 300 specialty vendors serving fresh sashimi, tamagoyaki, grilled scallops, and A5 Wagyu skewers."
    },
    {
        "poi_id": "JPN_08",
        "name": "Mount Fuji 5th Station & Lake Kawaguchiko",
        "city": "Japan",
        "state": "Yamanashi",
        "country": "Japan",
        "category": "Scenic Nature & Wonder",
        "rating": 4.9,
        "entry_fee_inr": 1500,
        "ideal_duration_hrs": 5.0,
        "lat": 35.3606,
        "lon": 138.7274,
        "tags": "mount fuji, lake cruise, ropeway, sacred mountain, alpine",
        "description": "Excursion to the scenic foothills and 5th station of sacred Mount Fuji, followed by a serene panoramic cable car ride over Lake Kawaguchiko."
    },
    {
        "poi_id": "JPN_09",
        "name": "Nara Deer Park & Tōdai-ji Giant Buddha",
        "city": "Japan",
        "state": "Nara",
        "country": "Japan",
        "category": "Heritage & Animals",
        "rating": 4.8,
        "entry_fee_inr": 450,
        "ideal_duration_hrs": 3.0,
        "lat": 34.6851,
        "lon": 135.8398,
        "tags": "bowing deer, colossal bronze buddha, ancient capital, park",
        "description": "Home to over 1,200 friendly, bowing sacred Sika deer and the grand Tōdai-ji temple housing the world's largest bronze statue of the Buddha."
    },
    {
        "poi_id": "JPN_10",
        "name": "Dotonbori & Shinsaibashi District",
        "city": "Japan",
        "state": "Osaka",
        "country": "Japan",
        "category": "Nightlife & Street Food",
        "rating": 4.7,
        "entry_fee_inr": 800,
        "ideal_duration_hrs": 3.0,
        "lat": 34.6687,
        "lon": 135.5013,
        "tags": "glico sign, takoyaki, okonomiyaki, canal cruise, neon night",
        "description": "Osaka's vibrant gastronomic capital illuminated by gigantic mechanical neon crab signs and the Glico running man, famed for crispy takoyaki and canal walks."
    },
    {
        "poi_id": "JPN_11",
        "name": "Meiji Jingu Shrine & Harajuku Takeshita Street",
        "city": "Japan",
        "state": "Tokyo",
        "country": "Japan",
        "category": "Culture & Pop Culture",
        "rating": 4.7,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.5,
        "lat": 35.6764,
        "lon": 139.6993,
        "tags": "tranquil forest shrine, cosplay, fashion boutiques, crepes",
        "description": "Tranquil 170-acre evergreen forest surrounding Emperor Meiji's sacred shrine, directly contrasting with the hyper-trendy Harajuku youth fashion district."
    },
    {
        "poi_id": "JPN_12",
        "name": "teamLab Planets Digital Art Museum",
        "city": "Japan",
        "state": "Tokyo",
        "country": "Japan",
        "category": "Modern Art & Tech",
        "rating": 4.9,
        "entry_fee_inr": 2200,
        "ideal_duration_hrs": 2.5,
        "lat": 35.6491,
        "lon": 139.7898,
        "tags": "digital art, immersive museum, crystal universe, mirror room",
        "description": "Groundbreaking immersive art experience where visitors walk barefoot through knee-deep water, infinite LED crystal universes, and floating orchid gardens."
    },
    {
        "poi_id": "JPN_13",
        "name": "Osaka Castle & Nishinomaru Garden",
        "city": "Japan",
        "state": "Osaka",
        "country": "Japan",
        "category": "Heritage & Fortress",
        "rating": 4.7,
        "entry_fee_inr": 500,
        "ideal_duration_hrs": 2.5,
        "lat": 34.6873,
        "lon": 135.5262,
        "tags": "samurai history, stone castle walls, cherry blossoms, moat",
        "description": "Iconic 16th-century fortress that played a pivotal role in the unification of Japan during the Azuchi-Momoyama period, surrounded by defensive stone moats."
    },
    {
        "poi_id": "JPN_14",
        "name": "Gion Geisha District & Pontocho Alley",
        "city": "Japan",
        "state": "Kyoto",
        "country": "Japan",
        "category": "Traditional Heritage & Dining",
        "rating": 4.8,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.5,
        "lat": 35.0037,
        "lon": 135.7772,
        "tags": "geisha, wooden machiya houses, lantern-lit alleys, kaiseki",
        "description": "Atmospheric historic entertainment district of Kyoto preserved with wooden machiya teahouses, stone-paved lanes, and traditional tea ceremonies."
    },
    {
        "poi_id": "JPN_15",
        "name": "Akihabara Electric Town & Maid Cafes",
        "city": "Japan",
        "state": "Tokyo",
        "country": "Japan",
        "category": "Pop Culture & Tech",
        "rating": 4.6,
        "entry_fee_inr": 600,
        "ideal_duration_hrs": 2.5,
        "lat": 35.6984,
        "lon": 139.7731,
        "tags": "anime, gaming, retro tech, collectibles, manga",
        "description": "The global Mecca for gaming, anime, manga, retro video game stores, and futuristic multi-story electronics department stores."
    },

    # ==================== SWITZERLAND (Zurich, Lucerne, Interlaken, Zermatt, Bern) ====================
    {
        "poi_id": "SWI_01",
        "name": "Zurich Old Town (Altstadt) & Lindenhof",
        "city": "Switzerland",
        "state": "Zurich",
        "country": "Europe",
        "category": "Heritage & Scenic",
        "rating": 4.8,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.5,
        "lat": 47.3717,
        "lon": 8.5422,
        "tags": "altstadt, cobblestone lanes, lindenhof hill view, fraumunster",
        "description": "Historic Roman hilltop viewpoint overlooking the Limmat River, Grossmünster twin towers, and Chagall stained glass at Fraumünster Church."
    },
    {
        "poi_id": "SWI_02",
        "name": "Lake Zurich Sunset Promenade & Cruise",
        "city": "Switzerland",
        "state": "Zurich",
        "country": "Europe",
        "category": "Scenic & Relaxation",
        "rating": 4.8,
        "entry_fee_inr": 1200,
        "ideal_duration_hrs": 2.0,
        "lat": 47.3667,
        "lon": 8.5417,
        "tags": "lake cruise, sunset promenade, swiss pass, swans, waterfront",
        "description": "Tranquil evening cruise on pristine glacial waters with alpine panoramas and elegant promenade strolls."
    },
    {
        "poi_id": "SWI_03",
        "name": "Chapel Bridge (Kapellbrücke) & Water Tower",
        "city": "Switzerland",
        "state": "Lucerne",
        "country": "Europe",
        "category": "Heritage",
        "rating": 4.8,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 1.5,
        "lat": 47.0516,
        "lon": 8.3075,
        "tags": "14th century wooden bridge, pictorial paintings, lake lucerne",
        "description": "Europe's oldest wooden covered footbridge spanning the Reuss River, adorned with 17th-century interior triangular paintings."
    },
    {
        "poi_id": "SWI_04",
        "name": "Mount Pilatus Golden Roundtrip Cableway",
        "city": "Switzerland",
        "state": "Lucerne",
        "country": "Europe",
        "category": "Adventure & Mountain",
        "rating": 4.9,
        "entry_fee_inr": 3500,
        "ideal_duration_hrs": 4.0,
        "lat": 46.9792,
        "lon": 8.2536,
        "tags": "steepest cogwheel railway, dragon mountain, panoramic cableway",
        "description": "Ascend on the world's steepest 48% gradient cogwheel railway to 2,132 meters elevation for 73 alpine peaks vistas."
    },
    {
        "poi_id": "SWI_05",
        "name": "Jungfraujoch - Top of Europe & Ice Palace",
        "city": "Switzerland",
        "state": "Interlaken",
        "country": "Europe",
        "category": "Wonder & Alpine",
        "rating": 5.0,
        "entry_fee_inr": 6500,
        "ideal_duration_hrs": 6.0,
        "lat": 46.5475,
        "lon": 7.9825,
        "tags": "sphinx observatory, 3454m railway, aletsch glacier, snow sports",
        "description": "High-altitude train journey to Europe's highest railway station at 3,454 meters, featuring the Sphinx terrace and Aletsch Glacier."
    },
    {
        "poi_id": "SWI_06",
        "name": "Lauterbrunnen Valley & Staubbach Falls",
        "city": "Switzerland",
        "state": "Interlaken",
        "country": "Europe",
        "category": "Nature & Waterfalls",
        "rating": 4.9,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 3.0,
        "lat": 46.5936,
        "lon": 7.9077,
        "tags": "72 waterfalls, tolkien inspiration, cliffside cascades",
        "description": "The 'Valley of 72 Waterfalls' flanked by sheer vertical limestone cliffs, highlighted by Staubbach Falls cascading 300 meters down."
    },
    {
        "poi_id": "SWI_07",
        "name": "Zermatt & Matterhorn Glacier Paradise",
        "city": "Switzerland",
        "state": "Zermatt",
        "country": "Europe",
        "category": "Iconic Alpine Wonder",
        "rating": 5.0,
        "entry_fee_inr": 5500,
        "ideal_duration_hrs": 5.0,
        "lat": 45.9763,
        "lon": 7.7491,
        "tags": "matterhorn, car-free alpine village, gornergrat cogwheel",
        "description": "Car-free Swiss village backdropped by the unmistakable pyramidal peak of the Matterhorn, accessed via the Gornergrat railway."
    },
    {
        "poi_id": "SWI_08",
        "name": "Bern Old City & Zytglogge Clock Tower",
        "city": "Switzerland",
        "state": "Bern",
        "country": "Europe",
        "category": "Heritage & UNESCO",
        "rating": 4.7,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.5,
        "lat": 46.9479,
        "lon": 7.4474,
        "tags": "unesco capital, sandstone arcades, astronomical clock, bear park",
        "description": "Switzerland's federal capital preserved with medieval sandstone arcades, ornate Renaissance fountains, and the 13th-century astronomical clock."
    },
    {
        "poi_id": "SWI_09",
        "name": "Lake Brienz Steamboat & Giessbach Falls",
        "city": "Switzerland",
        "state": "Interlaken",
        "country": "Europe",
        "category": "Scenic & Waterways",
        "rating": 4.8,
        "entry_fee_inr": 1800,
        "ideal_duration_hrs": 3.0,
        "lat": 46.7356,
        "lon": 8.0219,
        "tags": "turquoise lake, historic paddle steamer, cascading water",
        "description": "Cruise turquoise glacial waters on a vintage steamship to Giessbach Falls, which roar down 14 stages past the grand historic hotel."
    },
    {
        "poi_id": "SWI_10",
        "name": "Chillon Castle (Château de Chillon) on Lake Geneva",
        "city": "Switzerland",
        "state": "Montreux",
        "country": "Europe",
        "category": "Medieval Castle",
        "rating": 4.8,
        "entry_fee_inr": 1200,
        "ideal_duration_hrs": 2.5,
        "lat": 46.4142,
        "lon": 6.9275,
        "tags": "lake geneva fortress, lord byron, dungeons, alpine lakeside",
        "description": "Island castle sitting directly upon a rocky outcropping in Lake Geneva, occupied since the Bronze Age with 25 buildings and 3 courtyards."
    },

    # ==================== BALI (Ubud, Seminyak, Nusa Penida, Uluwatu, Canggu) ====================
    {
        "poi_id": "BAL_01",
        "name": "Tegallalang Rice Terraces & Jungle Swing",
        "city": "Bali",
        "state": "Ubud",
        "country": "Indonesia",
        "category": "Scenic Nature",
        "rating": 4.7,
        "entry_fee_inr": 300,
        "ideal_duration_hrs": 3.0,
        "lat": -8.4333,
        "lon": 115.2833,
        "tags": "subak irrigation, emerald terraces, jungle swing, photography",
        "description": "UNESCO-recognized subak agricultural terraces stepping down green ravines with exhilarating valley swings."
    },
    {
        "poi_id": "BAL_02",
        "name": "Sacred Monkey Forest Sanctuary",
        "city": "Bali",
        "state": "Ubud",
        "country": "Indonesia",
        "category": "Wildlife & Culture",
        "rating": 4.6,
        "entry_fee_inr": 450,
        "ideal_duration_hrs": 2.0,
        "lat": -8.5188,
        "lon": 115.2588,
        "tags": "macaques, ancient banyan trees, moss-covered statues",
        "description": "Lush jungle nature reserve housing over 1,000 Balinese long-tailed monkeys and 14th-century sacred temple complexes."
    },
    {
        "poi_id": "BAL_03",
        "name": "Uluwatu Cliff Temple & Kecak Fire Dance",
        "city": "Bali",
        "state": "Uluwatu",
        "country": "Indonesia",
        "category": "Culture & Sunset",
        "rating": 4.9,
        "entry_fee_inr": 750,
        "ideal_duration_hrs": 3.0,
        "lat": -8.8291,
        "lon": 115.0847,
        "tags": "70m cliff, sunset amphitheater, ramayana chant, ocean waves",
        "description": "Perched on a 70-meter limestone cliff plunging into the Indian Ocean, hosting the hypnotic sunset Kecak fire dance."
    },
    {
        "poi_id": "BAL_04",
        "name": "Nusa Penida Kelingking 'T-Rex' Beach & Broken Beach",
        "city": "Bali",
        "state": "Nusa Penida",
        "country": "Indonesia",
        "category": "Adventure & Island",
        "rating": 4.9,
        "entry_fee_inr": 1500,
        "ideal_duration_hrs": 6.0,
        "lat": -8.7508,
        "lon": 115.4746,
        "tags": "t-rex cliff, turquoise cove, manta ray snorkeling, speedboat",
        "description": "Day boat excursion to the dramatic T-Rex shaped limestone promontory dropping into white sands and turquoise waters."
    },
    {
        "poi_id": "BAL_05",
        "name": "Tanah Lot Sea Temple",
        "city": "Bali",
        "state": "Tabanan",
        "country": "Indonesia",
        "category": "Heritage & Sunset",
        "rating": 4.7,
        "entry_fee_inr": 350,
        "ideal_duration_hrs": 2.0,
        "lat": -8.6212,
        "lon": 115.0868,
        "tags": "sea offshore rock, crashing waves, sunset silhoutte",
        "description": "Ancient Hindu pilgrimage temple perched upon an offshore rock formation sculpted over centuries by ocean tides."
    },
    {
        "poi_id": "BAL_06",
        "name": "Mount Batur Sunrise Volcano Trek",
        "city": "Bali",
        "state": "Kintamani",
        "country": "Indonesia",
        "category": "Trekking & Adventure",
        "rating": 4.8,
        "entry_fee_inr": 2200,
        "ideal_duration_hrs": 5.0,
        "lat": -8.2422,
        "lon": 115.3753,
        "tags": "sunrise summit, volcanic caldera, steam vents, lake batur",
        "description": "Pre-dawn hike to the 1,717m summit of an active volcano to watch the sunrise above a sea of clouds and volcanic caldera."
    },
    {
        "poi_id": "BAL_07",
        "name": "Seminyak Beach Clubs & Canggu Sunset Vibes",
        "city": "Bali",
        "state": "Seminyak",
        "country": "Indonesia",
        "category": "Beach & Nightlife",
        "rating": 4.7,
        "entry_fee_inr": 1200,
        "ideal_duration_hrs": 3.5,
        "lat": -8.6913,
        "lon": 115.1537,
        "tags": "potato head, finns club, sunset beanbags, surfing, music",
        "description": "Relax on beachfront daybeds with chilled music, infinity pools, and world-class cocktails as the sun sinks into the sea."
    },
    {
        "poi_id": "BAL_08",
        "name": "Tirta Empul Holy Water Temple",
        "city": "Bali",
        "state": "Ubud",
        "country": "Indonesia",
        "category": "Spiritual & Heritage",
        "rating": 4.8,
        "entry_fee_inr": 250,
        "ideal_duration_hrs": 2.0,
        "lat": -8.4150,
        "lon": 115.3150,
        "tags": "holy spring, purification ritual, stone basins, carnelian koi",
        "description": "Historic Hindu water temple dating to 962 AD, famous for its sacred natural spring where travelers partake in purification baths."
    },

    # ==================== PARIS (Eiffel Tower, Louvre, Montmartre, Seine, Versailles) ====================
    {
        "poi_id": "PAR_01",
        "name": "Eiffel Tower & Champ de Mars",
        "city": "Paris",
        "state": "Ile-de-France",
        "country": "France",
        "category": "Iconic Landmark",
        "rating": 4.8,
        "entry_fee_inr": 2400,
        "ideal_duration_hrs": 3.0,
        "lat": 48.8584,
        "lon": 2.2945,
        "tags": "iron lady, summit elevator, sparkling lights, trocadero view",
        "description": "Gustave Eiffel's 330-meter iron masterpiece offering panoramic city vistas, champagne summit bars, and nightly sparkle shows."
    },
    {
        "poi_id": "PAR_02",
        "name": "Louvre Museum & Glass Pyramid",
        "city": "Paris",
        "state": "Ile-de-France",
        "country": "France",
        "category": "Art & History",
        "rating": 4.9,
        "entry_fee_inr": 1800,
        "ideal_duration_hrs": 4.0,
        "lat": 48.8606,
        "lon": 2.3376,
        "tags": "mona lisa, venus de milo, wing victory, i.m. pei pyramid",
        "description": "The world's most visited museum displaying over 35,000 masterpieces including Leonardo da Vinci's Mona Lisa."
    },
    {
        "poi_id": "PAR_03",
        "name": "Montmartre & Sacré-Cœur Basilica",
        "city": "Paris",
        "state": "Ile-de-France",
        "country": "France",
        "category": "Heritage & Bohemian",
        "rating": 4.8,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 3.0,
        "lat": 48.8867,
        "lon": 2.3431,
        "tags": "artists square, travertine basilica, panoramic hill, moulin rouge",
        "description": "Bohemian hilltop village where Picasso and Van Gogh painted, crowned by the Romano-Byzantine white domed Sacré-Cœur."
    },
    {
        "poi_id": "PAR_04",
        "name": "Seine River Evening Cruise & Pont Alexandre III",
        "city": "Paris",
        "state": "Ile-de-France",
        "country": "France",
        "category": "Scenic & Romance",
        "rating": 4.8,
        "entry_fee_inr": 1400,
        "ideal_duration_hrs": 2.0,
        "lat": 48.8640,
        "lon": 2.3135,
        "tags": "illuminated monuments, bateaux mouches, gilded statues",
        "description": "Glide under 37 bridges past Notre-Dame, the Musée d'Orsay, and the Grand Palais bathed in golden illuminations."
    },
    {
        "poi_id": "PAR_05",
        "name": "Palace of Versailles & Hall of Mirrors",
        "city": "Paris",
        "state": "Versailles",
        "country": "France",
        "category": "Royal Heritage",
        "rating": 4.9,
        "entry_fee_inr": 2200,
        "ideal_duration_hrs": 5.0,
        "lat": 48.8049,
        "lon": 2.1204,
        "tags": "hall of mirrors, royal gardens, fountains show, king louis xiv",
        "description": "Sun King Louis XIV's opulent 2,300-room royal chateau showcasing the 73-meter Hall of Mirrors and vast classical fountains."
    },
    {
        "poi_id": "PAR_06",
        "name": "Arc de Triomphe & Champs-Élysées",
        "city": "Paris",
        "state": "Ile-de-France",
        "country": "France",
        "category": "Monument & Luxury",
        "rating": 4.7,
        "entry_fee_inr": 1100,
        "ideal_duration_hrs": 2.0,
        "lat": 48.8738,
        "lon": 2.2950,
        "tags": "napoleonic arch, rooftop view, 12 radiating avenues, shopping",
        "description": "Napoleonic triumphal arch honoring French victories, offering rooftop views across the 12 radiating grand avenues."
    },
    {
        "poi_id": "PAR_07",
        "name": "Latin Quarter & Luxembourg Gardens",
        "city": "Paris",
        "state": "Ile-de-France",
        "country": "France",
        "category": "Parks & Historic",
        "rating": 4.7,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.5,
        "lat": 48.8462,
        "lon": 2.3372,
        "tags": "sorbonne, medici fountain, tree-lined gravel paths, bookshops",
        "description": "Historic student quarter filled with legendary cafes, Shakespeare & Company bookstore, and Marie de' Medici's palace gardens."
    },

    # ==================== MALDIVES ====================
    {
        "poi_id": "MLD_01",
        "name": "Maafushi Island Coral Reef Snorkeling",
        "city": "Maldives",
        "state": "South Male Atoll",
        "country": "Maldives",
        "category": "Marine & Water",
        "rating": 4.9,
        "entry_fee_inr": 2500,
        "ideal_duration_hrs": 4.0,
        "lat": 3.9405,
        "lon": 73.4907,
        "tags": "sea turtles, reef sharks, clownfish, clear waters, boat trip",
        "description": "Snorkel over pristine coral atolls with hawksbill sea turtles, harmless blacktip reef sharks, and schools of blue tangs."
    },
    {
        "poi_id": "MLD_02",
        "name": "Private Sandbank Picnic & Sunbed Relaxation",
        "city": "Maldives",
        "state": "Kaafu Atoll",
        "country": "Maldives",
        "category": "Luxury & Relaxation",
        "rating": 5.0,
        "entry_fee_inr": 4500,
        "ideal_duration_hrs": 3.5,
        "lat": 4.1755,
        "lon": 73.5093,
        "tags": "isolated sandbar, turquoise lagoon, gourmet lunch, privacy",
        "description": "Speedboat transfer to an uninhabited gleaming white sandbank surrounded by 360 degrees of crystal turquoise lagoon."
    },
    {
        "poi_id": "MLD_03",
        "name": "Sunset Dolphin Cruise & Glow Plankton Search",
        "city": "Maldives",
        "state": "North Male Atoll",
        "country": "Maldives",
        "category": "Wildlife & Scenic",
        "rating": 4.8,
        "entry_fee_inr": 2000,
        "ideal_duration_hrs": 2.5,
        "lat": 4.2100,
        "lon": 73.5400,
        "tags": "spinner dolphins, bow riding, bioluminescent shoreline",
        "description": "Cruise alongside pods of acrobatic wild spinner dolphins jumping beside the boat hull at sunset."
    },
    {
        "poi_id": "MLD_04",
        "name": "Overwater Villa Spa & Floating Breakfast",
        "city": "Maldives",
        "state": "Ari Atoll",
        "country": "Maldives",
        "category": "Wellness & Luxury",
        "rating": 4.9,
        "entry_fee_inr": 5000,
        "ideal_duration_hrs": 3.0,
        "lat": 3.8667,
        "lon": 72.8333,
        "tags": "floating breakfast tray, glass floor massage, private pool",
        "description": "Indulge in a signature tropical spa treatment with glass-floor viewing windows into the lagoon and floating infinity pool dining."
    },
    {
        "poi_id": "MLD_05",
        "name": "Male Heritage Tour & Old Friday Mosque",
        "city": "Maldives",
        "state": "Male",
        "country": "Maldives",
        "category": "Heritage & Culture",
        "rating": 4.5,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.0,
        "lat": 4.1773,
        "lon": 73.5133,
        "tags": "coral stone carvings, national museum, sultan park, fish market",
        "description": "Discover 1656 coral-stone architecture inscribed with Arabic calligraphy and browse the energetic local tuna fish market."
    },

    # ==================== DUBAI ====================
    {
        "poi_id": "DXB_01",
        "name": "Burj Khalifa At The Top (124th & 148th Floor)",
        "city": "Dubai",
        "state": "Dubai",
        "country": "UAE",
        "category": "Skyline & Landmark",
        "rating": 4.9,
        "entry_fee_inr": 3800,
        "ideal_duration_hrs": 2.5,
        "lat": 25.1972,
        "lon": 55.2744,
        "tags": "828m tower, world tallest, high speed elevator, desert view",
        "description": "Ascend the world's tallest building (828m) to enjoy panoramic views across the Arabian Gulf, desert dunes, and city skyline."
    },
    {
        "poi_id": "DXB_02",
        "name": "Dubai Mall, Aquarium & Dancing Fountain Show",
        "city": "Dubai",
        "state": "Dubai",
        "country": "UAE",
        "category": "Shopping & Entertainment",
        "rating": 4.8,
        "entry_fee_inr": 1500,
        "ideal_duration_hrs": 3.5,
        "lat": 25.1985,
        "lon": 55.2796,
        "tags": "giant aquarium tunnel, choreographed water show, luxury brands",
        "description": "Walk through a 48-meter aquarium tunnel surrounded by sand tiger sharks, followed by the world's largest choreographed music fountain."
    },
    {
        "poi_id": "DXB_03",
        "name": "Desert 4x4 Safari, Dune Bashing & Bedouin Camp",
        "city": "Dubai",
        "state": "Dubai",
        "country": "UAE",
        "category": "Adventure & Culture",
        "rating": 4.9,
        "entry_fee_inr": 2800,
        "ideal_duration_hrs": 6.0,
        "lat": 24.8333,
        "lon": 55.6667,
        "tags": "red dunes, quad bike, camel ride, tanoura dance, bbq buffet",
        "description": "High-octane dune bashing in Land Cruisers, sunset sandboarding, camel rides, and an authentic BBQ banquet under the desert stars."
    },
    {
        "poi_id": "DXB_04",
        "name": "Museum of the Future",
        "city": "Dubai",
        "state": "Dubai",
        "country": "UAE",
        "category": "Futuristic Tech",
        "rating": 4.8,
        "entry_fee_inr": 3200,
        "ideal_duration_hrs": 2.5,
        "lat": 25.2192,
        "lon": 55.2819,
        "tags": "arabic calligraphy torus, space station simulation, ai exhibits",
        "description": "An architectural marvel shaped like a silver torus adorned with Arabic calligraphy, exhibiting 2071 space and bioengineering technology."
    },
    {
        "poi_id": "DXB_05",
        "name": "Dubai Marina Yacht Cruise & Palm Jumeirah",
        "city": "Dubai",
        "state": "Dubai",
        "country": "UAE",
        "category": "Luxury & Cruise",
        "rating": 4.8,
        "entry_fee_inr": 2200,
        "ideal_duration_hrs": 2.5,
        "lat": 25.0805,
        "lon": 55.1403,
        "tags": "atlantis palm, luxury yacht, ain dubai wheel, skyline views",
        "description": "Sail past illuminated skyscrapers, Ain Dubai giant wheel, and the outer crescent of Palm Jumeirah on a luxury yacht."
    },
    {
        "poi_id": "DXB_06",
        "name": "Old Dubai, Gold & Spice Souks & Abra Ride",
        "city": "Dubai",
        "state": "Dubai",
        "country": "UAE",
        "category": "Heritage & Markets",
        "rating": 4.6,
        "entry_fee_inr": 100,
        "ideal_duration_hrs": 3.0,
        "lat": 25.2697,
        "lon": 55.2974,
        "tags": "creek crossing, saffron, frankincense, gold jewelry, al fahidi",
        "description": "Ride a traditional 1-dirham wooden abra across Dubai Creek to explore fragrant spice stalls, saffron vendors, and dazzling gold bazaars."
    },

    # ==================== GOA ====================
    {
        "poi_id": "GOA_01",
        "name": "Baga Beach & Watersports Hub",
        "city": "Goa",
        "state": "Goa",
        "country": "India",
        "category": "Beach & Watersports",
        "rating": 4.5,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 3.5,
        "lat": 15.5553,
        "lon": 73.7516,
        "tags": "parasailing, jet-ski, beach shacks, seafood",
        "description": "High-energy beach in North Goa with iconic beach clubs, watersports (parasailing, jet-ski), seafood shacks, and vibrant night clubs."
    },
    {
        "poi_id": "GOA_02",
        "name": "Fort Aguada & 17th Century Lighthouse",
        "city": "Goa",
        "state": "Goa",
        "country": "India",
        "category": "Heritage & Scenic",
        "rating": 4.6,
        "entry_fee_inr": 50,
        "ideal_duration_hrs": 2.0,
        "lat": 15.4921,
        "lon": 73.7736,
        "tags": "portuguese fort, lighthouse, ocean view, photography",
        "description": "A 17th-century Portuguese fortress standing on Sinquerim Beach overlooking the Arabian Sea, featuring a historic four-storey lighthouse."
    },
    {
        "poi_id": "GOA_03",
        "name": "Basilica of Bom Jesus & Se Cathedral",
        "city": "Goa",
        "state": "Goa",
        "country": "India",
        "category": "Heritage & Culture",
        "rating": 4.8,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.0,
        "lat": 15.5009,
        "lon": 73.9116,
        "tags": "unesco, baroque architecture, mortal remains of st. francis xavier",
        "description": "UNESCO World Heritage landmark in Old Goa housing the mortal remains of St. Francis Xavier, renowned for exquisite Baroque architecture."
    },
    {
        "poi_id": "GOA_04",
        "name": "Dudhsagar Falls & Jungle Jeep Safari",
        "city": "Goa",
        "state": "Goa",
        "country": "India",
        "category": "Nature & Adventure",
        "rating": 4.8,
        "entry_fee_inr": 800,
        "ideal_duration_hrs": 5.0,
        "lat": 15.3144,
        "lon": 74.3143,
        "tags": "four-tiered waterfall, sea of milk, railway bridge, jungle trek",
        "description": "Spectacular 310m four-tiered cascade on the Mandovi River, accessible via 4x4 jungle jeep safari through Bhagwan Mahavir Wildlife Sanctuary."
    },
    {
        "poi_id": "GOA_05",
        "name": "Anjuna Flea Market & Curlies Sunset Shack",
        "city": "Goa",
        "state": "Goa",
        "country": "India",
        "category": "Bohemian & Sunset",
        "rating": 4.6,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 3.0,
        "lat": 15.5733,
        "lon": 73.7410,
        "tags": "hippie flea market, live music, rocky cliff, sunset cocktails",
        "description": "Famous bohemian beach with rock formations, Wednesday flea market stalls, handcrafted jewelry, and laid-back sunset shacks."
    },
    {
        "poi_id": "GOA_06",
        "name": "Palolem Beach & Silent Noise Headphone Party",
        "city": "Goa",
        "state": "Goa",
        "country": "India",
        "category": "Scenic Beach & Relaxation",
        "rating": 4.8,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 3.5,
        "lat": 15.0100,
        "lon": 74.0232,
        "tags": "crescent beach, calm swimming waters, kayak to butterfly beach",
        "description": "Pristine crescent bay in South Goa with calm swimming waters, colorful beachfront wooden cottages, and kayak tours to Butterfly Island."
    },
    {
        "poi_id": "GOA_07",
        "name": "Fontainhas Latin Quarter Walking Tour",
        "city": "Goa",
        "state": "Goa",
        "country": "India",
        "category": "Heritage & Architecture",
        "rating": 4.7,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.0,
        "lat": 15.4989,
        "lon": 73.8322,
        "tags": "portuguese houses, colorful alleys, bakeries, azulejos tiles",
        "description": "Asia's only surviving Latin Quarter featuring narrow winding streets, pastel-painted 18th-century Portuguese mansions, and artisan bakeries."
    },
    {
        "poi_id": "GOA_08",
        "name": "Sahakari Spice Farm Guided Tour & Goan Buffet",
        "city": "Goa",
        "state": "Goa",
        "country": "India",
        "category": "Culinary & Nature",
        "rating": 4.6,
        "entry_fee_inr": 500,
        "ideal_duration_hrs": 2.5,
        "lat": 15.4056,
        "lon": 74.0203,
        "tags": "cardamom, vanilla, elephant bath, authentic goan lunch on banana leaf",
        "description": "Walk through dense aromatic plantations of vanilla, cinnamon, and betel nut, concluded with traditional Goan lunch and feni tasting."
    },

    # ==================== JAIPUR ====================
    {
        "poi_id": "JAI_01",
        "name": "Amber Fort (Amer Palace) & Sheesh Mahal",
        "city": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "category": "Heritage & Fortress",
        "rating": 4.8,
        "entry_fee_inr": 200,
        "ideal_duration_hrs": 3.5,
        "lat": 26.9855,
        "lon": 75.8513,
        "tags": "mirror palace, mughal-rajput architecture, maota lake view",
        "description": "Majestic hilltop fort built of red sandstone and marble, containing the Sheesh Mahal mirror palace with intricate mosaics."
    },
    {
        "poi_id": "JAI_02",
        "name": "Hawa Mahal (Palace of Winds)",
        "city": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "category": "Heritage & Architecture",
        "rating": 4.6,
        "entry_fee_inr": 50,
        "ideal_duration_hrs": 1.5,
        "lat": 26.9239,
        "lon": 75.8267,
        "tags": "953 jharokhas windows, pink sandstone, honeycomb facade",
        "description": "Five-storey pink sandstone palace with 953 honeycomb windows designed to let royal ladies observe street festivals unseen."
    },
    {
        "poi_id": "JAI_03",
        "name": "City Palace & Chandra Mahal Museum",
        "city": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "category": "Royal Heritage",
        "rating": 4.7,
        "entry_fee_inr": 300,
        "ideal_duration_hrs": 2.5,
        "lat": 26.9258,
        "lon": 75.8236,
        "tags": "royal residence, peacock gate, armory museum, courtyards",
        "description": "Vast royal palace complex featuring courtyards, the famous Peacock Gate, and museums displaying royal costumes and weaponry."
    },
    {
        "poi_id": "JAI_04",
        "name": "Jantar Mantar Astronomical Observatory",
        "city": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "category": "UNESCO Science & History",
        "rating": 4.7,
        "entry_fee_inr": 100,
        "ideal_duration_hrs": 2.0,
        "lat": 26.9248,
        "lon": 75.8246,
        "tags": "unesco, largest stone sundial, 18th century astronomy",
        "description": "UNESCO World Heritage collection of 19 architectural astronomical instruments built by Maharaja Sawai Jai Singh II in 1734."
    },
    {
        "poi_id": "JAI_05",
        "name": "Nahargarh Fort Sunset Viewpoint",
        "city": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "category": "Scenic & Sunset",
        "rating": 4.8,
        "entry_fee_inr": 100,
        "ideal_duration_hrs": 2.5,
        "lat": 26.9372,
        "lon": 75.8155,
        "tags": "aravalli hills, panoramic pink city view, rooftop cafe, stepwell",
        "description": "Hilltop bastion along the Aravalli ridge providing the finest panoramic sunset view over the entire illuminated Pink City."
    },
    {
        "poi_id": "JAI_06",
        "name": "Jal Mahal (Water Palace) & Lake Promenade",
        "city": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "category": "Scenic & Photography",
        "rating": 4.5,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 1.5,
        "lat": 26.9535,
        "lon": 75.8462,
        "tags": "floating palace, man sagar lake, camel rides, street photography",
        "description": "Architectural marvel appearing to float in the middle of Man Sagar Lake, surrounded by the picturesque Aravalli range."
    },
    {
        "poi_id": "JAI_07",
        "name": "Johari Bazaar & Bapu Bazaar Shopping",
        "city": "Jaipur",
        "state": "Rajasthan",
        "country": "India",
        "category": "Bazaars & Souvenirs",
        "rating": 4.6,
        "entry_fee_inr": 0,
        "ideal_duration_hrs": 2.5,
        "lat": 26.9196,
        "lon": 75.8262,
        "tags": "gemstones, blue pottery, jaipuri quilts, mojari leather shoes",
        "description": "Ancient pink-walled bazaar famous for authentic Kundan jewelry, handcrafted Jaipuri razai quilts, blue pottery, and street kachoris."
    }
]

def save_all():
    os.makedirs("datasets/destinations", exist_ok=True)
    with open("datasets/destinations/destinations_rich_knowledge.json", "w", encoding="utf-8") as f:
        json.dump(ALL_DESTINATIONS_POIS, f, indent=2, ensure_ascii=False)
    print(f"Saved {len(ALL_DESTINATIONS_POIS)} rich authentic POIs across global & domestic destinations!")

if __name__ == "__main__":
    save_all()
